[package]
authors = ["you"]
build = "src/build.rs"
default-run = "app"
description = "A Tauri App"
<<<<<<< HEAD
edition = "2018"
=======
authors = ["you"]
>>>>>>> parent of 6206ad8 (Add a bit more of everything including upload progress for Avatar (GIFS))
license = ""
name = "app"
repository = ""
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {version = "1.0.0-beta.4"}

[dependencies]
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
<<<<<<< HEAD
soloud = {git = "https://github.com/moalyousef/soloud-rs"}
tauri = {git = "https://github.com/tauri-apps/tauri", branch = "next", features = ["api-all"], version = "1.0.0-beta.8"}
winapi = {version = "0.3.9", features = ["shellscalingapi"] }
cpal = { version = "*" }
=======
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
winapi = { version = "0.3.9", features = [ "shellscalingapi" ] }
>>>>>>> parent of 6206ad8 (Add a bit more of everything including upload progress for Avatar (GIFS))

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
